### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by OldFatBoy** [suvllian/process-inject#1]
前辈，您好，我有些问题想请教您，希望您能抽空给些思路，万分感谢。

我一直做的时LINUX底层开发，对Windows的开发没有思路。我现在想做一个USB管理程序，程序功能如下：
1. 程序发现USB（PnP设备）加载，并获取USB设备的信息
2. 程序通过HOOK函数暂时中断设备加载的流程，并进行自己的逻辑处理。
3. 程序根据黑白名单进行设备校验，如果校验通过则继续进行加载流程，否则终止加载流程。

我的疑问：
1. 程序使用C进行开发，可以通过哪些Windows库或者模块获取设备加载信息并获取设备信息
2. 该程序是否需要用Windows内核来实现
3. Windows的Hook函数接口有哪些，是否有资料。
4. 哪些接口可以实现设备加载流程的中断.

谢谢您，给您带来不便请谅解。

**Comment by suvllian** [comment]
你好，抱歉今天才回复你。Windows驱动开发我只是写过一点点代码，之后就没有做过驱动开发了。

你想要开发Windows的USB管理程序的话，推荐你去看张帆的《Windows驱动开发技术详解》，其中第17章专门介绍了WIndows对USB设备驱动。

对于你的问题：

  1、建议参考《Windows驱动开发技术详解》第四章。
  2、我个人理解是需要用内核函数去处理的。
  3、建议参考《Windows驱动开发技术详解》第六章和第七章。
  4、设备加载流程中断具体我不大清楚，不过在《Windows驱动开发技术详解》书中应该能找到答案。

因为很长时间没有做windows开发了，所以都生疏了，帮不到太多，建议你去看书学习下，书上讲解也很详细。如果你需要《Windows驱动开发技术详解》这本书的PDF版本的话，请留言，我会发到你的邮箱。感谢你的提问。

**Comment by TTtaosen** [comment]
前辈你好，我最近再学习编写一些简单的程序，我希望它能够包含进程注入的功能来实现隐藏自己的能力。

我编写了一个简单的dll来测试是否能够注入进程。
``
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

FILE* CreateMyFile(char fileName[]);
void run();
BOOL APIENTRY DllMain( HANDLE hModule, 
                       DWORD  ul_reason_for_call, 
                       LPVOID lpReserved
					 )
{
printf("hModule.%p lpReserved.%p \n", hModule,lpReserved);	
	switch (ul_reason_for_call)	{		
	case DLL_PROCESS_ATTACH:
		while(1){
		MessageBox(0,"hello wordld","hello",0);
		}
		run();
		break;		
	case DLL_PROCESS_DETACH:			
		printf("Process detach. \n");			
		break;		
	case DLL_THREAD_ATTACH:			
		printf("Thread attach. \n");			
		break;		
	case DLL_THREAD_DETACH:			
		printf("Thread detach. \n");			
		break;	
	}	
	return (TRUE);
}
``
然后使用项目中的remotethread来测试运行。
事实上不仅测试了remotethread还有其他一些程序包括自己写的注入程序。
但是结果并没有达到预期。并没有任何弹窗，而且通过processexp并为看见进程中出现相应的dll
而且事实上通过rundll32.exe运行dll也不能实现功能。
这让我很疑惑。
我使用的平台为 winxp sp3（虚拟机），VC++ 6.0
同样也在win10 平台下使用vs2017测试过您的代码，同样无法得到预期的目标
特地来请教
我的联系方式：673918781@qq.com

**Comment by suvllian** [comment]
你好，

**你测试的过程中修改了remotethread中dll的路径了吗？**

![image](https://user-images.githubusercontent.com/18010304/49130525-4acfee00-f30f-11e8-931b-b691e88dd9ed.png)

如果你在win10系统上测试的话，你需要修改remotethread中的dll路径，然后把remotethread和dll中的函数改成unicode版本，然后编译64位版本，在win10下就可以测试了。

**Comment by TTtaosen** [comment]
你好，我已经解决了我的问题。确实是因为dll路径的原因。对windows编程并不熟练导致的结果。
然而在win10下又遇到了一个问题：
win10中如果要对系统文件进行修改，例如使用regValue等函数需要程序“以管理员权限运行”，有什么方法可以绕过他吗？

**Comment by suvllian** [comment]
> 你好，我已经解决了我的问题。确实是因为dll路径的原因。对windows编程并不熟练导致的结果。
> 然而在win10下又遇到了一个问题：
> win10中如果要对系统文件进行修改，例如使用regValue等函数需要程序“以管理员权限运行”，有什么方法可以绕过他吗？

在Vs设置uac权限即可
